### PR TITLE
fix(elements): update scraper to get attributes from AST

### LINKED ISSUE #27: Add support for entity_autocomplete form element in autocomplete
When using `@FormElement` to autocomplete form elements, the `entity_autocomplete` element is missing. 

The scraper needs to add `/core/lib/Drupal/Core/Entity/Element/` to include it.

thanks,
-mike

### PR DESCRIPTION
**Pull request by andy-blum**
Closes #27

Uses [PHP attributes](https://www.php.net/manual/en/language.attributes.php) to get element names

### CODE REVIEW

**Comment by ultimike** [comment]
Cool. Thanks. Is there an easy way to get this before the next release?

**Comment by andy-blum** [comment]
If you scan the changes in the JSON file and think it looks good I'll just release a new version

**Comment by ultimike** [comment]
The underscore stuff looks reasonable, but I did notice a bunch of changes similar to:

```
-      "@FormElement (\"link\")",
+      "@RenderElement (\"link\")",
```

Where it changes from `FormElement` to `RenderElement`. Are these correct? 

-mike

**Comment by andy-blum** [comment]
This is correct - we went off the rails in #31.

Screenshot 2024-10-24 at 8 58 26 PM

**Pull request merged**
